FROM node:18-alpine
WORKDIR /app/

ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PATH:$PNPM_HOME
RUN npm i -g pnpm
RUN pnpm add -g @nestjs/cli

EXPOSE 3000
ENV NODE_PORT 3000
ENV NODE_ENV dev
ENTRYPOINT [ "pnpm", "run" ]
CMD [ "start:prod" ]
